"""Provider throughput limits shared by runtimes and immutable Preview builds."""

GEMINI_REQUESTS_PER_MINUTE_PER_KEY = 12
GEMINI_SAFE_INPUT_TOKENS_PER_MINUTE_TOTAL = 225_000
GEMMA_SAFE_REQUESTS_PER_MINUTE_PER_ACCOUNT = 20
GEMMA_SAFE_INPUT_TOKENS_PER_MINUTE_PER_ACCOUNT = 15_000
GEMMA_PROVIDER_LANES_PER_ACCOUNT = 2
