"""Compatibility shim for xauusd_forecaster.assistant.agent."""

from xauusd_forecaster.assistant.agent import (
    ASSISTANT_AGENT_BUDGETS_ENV,
    ASSISTANT_AGENT_POLICY_VERSION,
    ASSISTANT_AGENT_SYSTEM_INSTRUCTION_VERSION,
    AssistantAgentBudgets,
    AssistantAgentContractError,
    AssistantAgentRequest,
    AssistantAgentResult,
    AssistantModelTurn,
    AssistantModelTurnInvoker,
    AssistantToolResultObserver,
    CapacityRoutedAssistantModelInvoker,
    DEFAULT_ASSISTANT_AGENT_BUDGETS,
    DEFAULT_ASSISTANT_SYSTEM_INSTRUCTION,
    MAX_TOOL_ROUNDS_PER_USER_TURN,
    RoutedAssistantModelTurn,
    configured_assistant_agent_budgets,
    decode_gemini_assistant_turn,
    decode_ollama_assistant_turn,
    ollama_openai_payload,
    run_bounded_assistant_agent,
    run_capacity_routed_assistant_agent,
)

__all__ = [
    "ASSISTANT_AGENT_BUDGETS_ENV",
    "ASSISTANT_AGENT_POLICY_VERSION",
    "ASSISTANT_AGENT_SYSTEM_INSTRUCTION_VERSION",
    "AssistantAgentBudgets",
    "AssistantAgentContractError",
    "AssistantAgentRequest",
    "AssistantAgentResult",
    "AssistantModelTurn",
    "AssistantModelTurnInvoker",
    "AssistantToolResultObserver",
    "CapacityRoutedAssistantModelInvoker",
    "DEFAULT_ASSISTANT_AGENT_BUDGETS",
    "DEFAULT_ASSISTANT_SYSTEM_INSTRUCTION",
    "MAX_TOOL_ROUNDS_PER_USER_TURN",
    "RoutedAssistantModelTurn",
    "configured_assistant_agent_budgets",
    "decode_gemini_assistant_turn",
    "decode_ollama_assistant_turn",
    "ollama_openai_payload",
    "run_bounded_assistant_agent",
    "run_capacity_routed_assistant_agent",
]
