"""Compatibility shim for xauusd_forecaster.assistant.capacity."""

from xauusd_forecaster.assistant.capacity import (
    ASSISTANT_CAPACITY_POLICIES_ENV,
    ASSISTANT_CAPACITY_POLICY_VERSION,
    ASSISTANT_CAPACITY_SCHEMA,
    AssistantCapacityPolicy,
    AssistantCapacityReservation,
    AssistantCapacityResult,
    AssistantCapacityUnavailable,
    AssistantServicePriority,
    DEFAULT_COOLDOWN_SECONDS,
    DEFAULT_FAILURE_COOLDOWN_THRESHOLD,
    DEFAULT_MAX_IN_FLIGHT,
    DEFAULT_RESERVATION_TTL_SECONDS,
    DEFAULT_SOFT_CAP_BASIS_POINTS,
    MAX_ASSISTANT_CAPACITY_ATTEMPTS,
    MAX_ASSISTANT_CREDENTIAL_POOLS,
    MAX_CAPACITY_POLICIES,
    MAX_CREDENTIALS_PER_POOL,
    PreReservedAssistantAccountant,
    T,
    configured_assistant_capacity_policies,
    credential_pool_fingerprint,
    execute_assistant_capacity_route,
    install_assistant_capacity_schema,
)

__all__ = [
    "ASSISTANT_CAPACITY_POLICIES_ENV",
    "ASSISTANT_CAPACITY_POLICY_VERSION",
    "ASSISTANT_CAPACITY_SCHEMA",
    "AssistantCapacityPolicy",
    "AssistantCapacityReservation",
    "AssistantCapacityResult",
    "AssistantCapacityUnavailable",
    "AssistantServicePriority",
    "DEFAULT_COOLDOWN_SECONDS",
    "DEFAULT_FAILURE_COOLDOWN_THRESHOLD",
    "DEFAULT_MAX_IN_FLIGHT",
    "DEFAULT_RESERVATION_TTL_SECONDS",
    "DEFAULT_SOFT_CAP_BASIS_POINTS",
    "MAX_ASSISTANT_CAPACITY_ATTEMPTS",
    "MAX_ASSISTANT_CREDENTIAL_POOLS",
    "MAX_CAPACITY_POLICIES",
    "MAX_CREDENTIALS_PER_POOL",
    "PreReservedAssistantAccountant",
    "T",
    "configured_assistant_capacity_policies",
    "credential_pool_fingerprint",
    "execute_assistant_capacity_route",
    "install_assistant_capacity_schema",
]
