"""Compatibility shim for xauusd_forecaster.assistant.compaction."""

from xauusd_forecaster.assistant.compaction import (
    ASSISTANT_COMPACTION_MAX_OUTPUT_TOKENS,
    ASSISTANT_COMPACTION_PROMPT_VERSION,
    ASSISTANT_PIN_KINDS,
    MAX_EXISTING_PINS,
    MAX_GENERATED_PINS,
    MAX_INPUT_CHARACTERS,
    MAX_PIN_CONTENT_CHARACTERS,
    MAX_REFERENCE_ITEMS,
    MAX_SOURCE_MESSAGES,
    MAX_SUMMARY_CHARACTERS,
    compact_assistant_context,
)

__all__ = [
    "ASSISTANT_COMPACTION_MAX_OUTPUT_TOKENS",
    "ASSISTANT_COMPACTION_PROMPT_VERSION",
    "ASSISTANT_PIN_KINDS",
    "MAX_EXISTING_PINS",
    "MAX_GENERATED_PINS",
    "MAX_INPUT_CHARACTERS",
    "MAX_PIN_CONTENT_CHARACTERS",
    "MAX_REFERENCE_ITEMS",
    "MAX_SOURCE_MESSAGES",
    "MAX_SUMMARY_CHARACTERS",
    "compact_assistant_context",
]
