"""Compatibility shim for xauusd_forecaster.assistant.routing."""

from xauusd_forecaster.assistant.routing import (
    ASSISTANT_MODEL_PROFILES_ENV,
    ASSISTANT_REQUEST_ENVELOPE_RESERVE,
    ASSISTANT_ROUTING_POLICY_VERSION,
    AssistantModelRoutingUnavailable,
    AssistantRoutePlan,
    AssistantTaskType,
    AssistantToolPolicy,
    DEFAULT_ASSISTANT_MODEL_PROFILES,
    GOOGLE_GENERATIVE_LANGUAGE,
    INSTALLED_ASSISTANT_PROVIDERS,
    MAX_ASSISTANT_MODEL_CANDIDATES,
    ModelCapacityClass,
    ModelProfile,
    ModelRequirement,
    OLLAMA_LOCAL,
    ReasoningClass,
    ThinkingLevel,
    apply_provider_thinking_level,
    classify_assistant_reasoning,
    classify_assistant_tool_policy,
    configured_assistant_model_profiles,
    conservative_assistant_token_estimate,
    plan_assistant_route,
    provider_thinking_level,
    routing_provenance,
)

__all__ = [
    "ASSISTANT_MODEL_PROFILES_ENV",
    "ASSISTANT_REQUEST_ENVELOPE_RESERVE",
    "ASSISTANT_ROUTING_POLICY_VERSION",
    "AssistantModelRoutingUnavailable",
    "AssistantRoutePlan",
    "AssistantTaskType",
    "AssistantToolPolicy",
    "DEFAULT_ASSISTANT_MODEL_PROFILES",
    "GOOGLE_GENERATIVE_LANGUAGE",
    "INSTALLED_ASSISTANT_PROVIDERS",
    "MAX_ASSISTANT_MODEL_CANDIDATES",
    "ModelCapacityClass",
    "ModelProfile",
    "ModelRequirement",
    "OLLAMA_LOCAL",
    "ReasoningClass",
    "ThinkingLevel",
    "apply_provider_thinking_level",
    "classify_assistant_reasoning",
    "classify_assistant_tool_policy",
    "configured_assistant_model_profiles",
    "conservative_assistant_token_estimate",
    "plan_assistant_route",
    "provider_thinking_level",
    "routing_provenance",
]
