"""Compatibility shim for xauusd_forecaster.news.brief.product."""

from xauusd_forecaster.news.brief.product import (
    BRIEF_ACCUMULATION_AGE,
    BRIEF_BACKLOG_LIMIT,
    BRIEF_CAPACITY_RETRY,
    BRIEF_EVIDENCE_LIMIT,
    BRIEF_FAILURE_ATTEMPT_LIMIT,
    BRIEF_FAILURE_RETRY_MAX,
    BRIEF_INPUT_TOKEN_BUDGET,
    BRIEF_MAJOR_EVENT_AGE,
    BRIEF_NORMAL_STALENESS,
    BRIEF_OUTPUT_TOKEN_BUDGET,
    BRIEF_PROGRESS_BOUNDARY,
    BRIEF_PROMPT_VERSION,
    BRIEF_QUIET_STALENESS,
    BRIEF_RECOVERY_VERSION,
    BRIEF_STARVATION_AGE,
    DailyBriefEvidenceContractFailed,
    FINAL_PHASES,
    GENERATION_FAILURE_CODES,
    KUALA_LUMPUR,
    brief_dates_to_process,
    daily_brief_summary,
    recent_daily_briefs,
    update_daily_brief,
)

__all__ = [
    "BRIEF_ACCUMULATION_AGE",
    "BRIEF_BACKLOG_LIMIT",
    "BRIEF_CAPACITY_RETRY",
    "BRIEF_EVIDENCE_LIMIT",
    "BRIEF_FAILURE_ATTEMPT_LIMIT",
    "BRIEF_FAILURE_RETRY_MAX",
    "BRIEF_INPUT_TOKEN_BUDGET",
    "BRIEF_MAJOR_EVENT_AGE",
    "BRIEF_NORMAL_STALENESS",
    "BRIEF_OUTPUT_TOKEN_BUDGET",
    "BRIEF_PROGRESS_BOUNDARY",
    "BRIEF_PROMPT_VERSION",
    "BRIEF_QUIET_STALENESS",
    "BRIEF_RECOVERY_VERSION",
    "BRIEF_STARVATION_AGE",
    "DailyBriefEvidenceContractFailed",
    "FINAL_PHASES",
    "GENERATION_FAILURE_CODES",
    "KUALA_LUMPUR",
    "brief_dates_to_process",
    "daily_brief_summary",
    "recent_daily_briefs",
    "update_daily_brief",
]
