"""Compatibility shim for xauusd_forecaster.ai.model_limits."""

from xauusd_forecaster.ai.model_limits import (
    GEMINI_REQUESTS_PER_MINUTE_PER_KEY,
    GEMINI_SAFE_INPUT_TOKENS_PER_MINUTE_TOTAL,
    GEMMA_PROVIDER_LANES_PER_ACCOUNT,
    GEMMA_SAFE_INPUT_TOKENS_PER_MINUTE_PER_ACCOUNT,
    GEMMA_SAFE_REQUESTS_PER_MINUTE_PER_ACCOUNT,
)

__all__ = [
    "GEMINI_REQUESTS_PER_MINUTE_PER_KEY",
    "GEMINI_SAFE_INPUT_TOKENS_PER_MINUTE_TOTAL",
    "GEMMA_PROVIDER_LANES_PER_ACCOUNT",
    "GEMMA_SAFE_INPUT_TOKENS_PER_MINUTE_PER_ACCOUNT",
    "GEMMA_SAFE_REQUESTS_PER_MINUTE_PER_ACCOUNT",
]
