"""Compatibility shim for xauusd_forecaster.news.annotation.impact."""

from xauusd_forecaster.news.annotation.impact import (
    EVENT_STATES,
    HANDOVER_IMPACT_PROMPT_VERSION,
    IDENTITY_CANDIDATE_UNIVERSE_LIMIT,
    IDENTITY_RELATIONS,
    IMPACT_CLASSES,
    IMPACT_MODEL,
    IMPACT_PROMPT_VERSION,
    IMPACT_RESPONSE_SCHEMA,
    IMPACT_TIME_RULES,
    UPDATE_TYPES,
    build_identity_candidate_index,
    impact_is_actionable,
    impact_time_rule,
    load_identity_candidate_universe,
    materialize_identity_candidate,
    pending_impact_records,
    prior_identity_similarity,
    public_impact_reason,
    retrieve_prior_event_context,
    validate_impact_assessment,
)

__all__ = [
    "EVENT_STATES",
    "HANDOVER_IMPACT_PROMPT_VERSION",
    "IDENTITY_CANDIDATE_UNIVERSE_LIMIT",
    "IDENTITY_RELATIONS",
    "IMPACT_CLASSES",
    "IMPACT_MODEL",
    "IMPACT_PROMPT_VERSION",
    "IMPACT_RESPONSE_SCHEMA",
    "IMPACT_TIME_RULES",
    "UPDATE_TYPES",
    "build_identity_candidate_index",
    "impact_is_actionable",
    "impact_time_rule",
    "load_identity_candidate_universe",
    "materialize_identity_candidate",
    "pending_impact_records",
    "prior_identity_similarity",
    "public_impact_reason",
    "retrieve_prior_event_context",
    "validate_impact_assessment",
]
