"""Compatibility shim for xauusd_forecaster.news.retrieval.search."""

from xauusd_forecaster.news.retrieval.search import (
    HybridRetrievalResult,
    NEWS_BACKFILL_BATCH,
    NEWS_BACKFILL_COOLDOWN_BASE_SECONDS,
    NEWS_BACKFILL_COOLDOWN_MAX_SECONDS,
    NEWS_BACKFILL_LEASE_SECONDS,
    NEWS_DETERMINISTIC_FALLBACK_VERSION,
    NEWS_EMBEDDING_DIMENSIONS,
    NEWS_EMBEDDING_MODEL,
    NEWS_EMBEDDING_TEXT_VERSION,
    NEWS_HYBRID_RETRIEVAL_VERSION,
    NEWS_RETRIEVAL_PRESSURE_WINDOW,
    NEWS_RETRIEVAL_RECOVERY_STABILIZATION,
    NEWS_ROUTE_LIMIT,
    NewsEmbeddingBackfillPending,
    NewsEmbeddingPrerequisiteCooldown,
    append_missing_embeddings,
    attach_hybrid_prior_event_context,
    identity_embedding_text,
    latest_embedding_profile,
    lexical_identity_similarity,
    lexical_identity_tokens,
    load_embeddings,
    retrieve_hybrid_prior_event_context,
)

__all__ = [
    "HybridRetrievalResult",
    "NEWS_BACKFILL_BATCH",
    "NEWS_BACKFILL_COOLDOWN_BASE_SECONDS",
    "NEWS_BACKFILL_COOLDOWN_MAX_SECONDS",
    "NEWS_BACKFILL_LEASE_SECONDS",
    "NEWS_DETERMINISTIC_FALLBACK_VERSION",
    "NEWS_EMBEDDING_DIMENSIONS",
    "NEWS_EMBEDDING_MODEL",
    "NEWS_EMBEDDING_TEXT_VERSION",
    "NEWS_HYBRID_RETRIEVAL_VERSION",
    "NEWS_RETRIEVAL_PRESSURE_WINDOW",
    "NEWS_RETRIEVAL_RECOVERY_STABILIZATION",
    "NEWS_ROUTE_LIMIT",
    "NewsEmbeddingBackfillPending",
    "NewsEmbeddingPrerequisiteCooldown",
    "append_missing_embeddings",
    "attach_hybrid_prior_event_context",
    "identity_embedding_text",
    "latest_embedding_profile",
    "lexical_identity_similarity",
    "lexical_identity_tokens",
    "load_embeddings",
    "retrieve_hybrid_prior_event_context",
]
