"""Compatibility shim for xauusd_forecaster.news.semantics.transitions."""

from xauusd_forecaster.news.semantics.transitions import (
    ARCHIVAL_ONLY,
    CURRENT_OPERATIONAL,
    DECLARED_TRANSITIONS,
    DEMAND_CLASSES,
    DETERMINISTIC_MIGRATION,
    DETERMINISTIC_MIGRATORS,
    MODEL_REVIEW_REQUIRED,
    REUSE_COMPATIBLE,
    SemanticTransition,
    SemanticTransitionContract,
    SemanticTransitionContractChanged,
    TRAINING_REQUIRED,
    TRANSITION_CONTRACT_VERSION,
    TRANSITION_KINDS,
    demand_allows_scheduling,
    execute_transition_page,
    provider_dispatches_for_transition,
    requires_model_review,
    semantic_transition_contract,
    transition_for,
)

__all__ = [
    "ARCHIVAL_ONLY",
    "CURRENT_OPERATIONAL",
    "DECLARED_TRANSITIONS",
    "DEMAND_CLASSES",
    "DETERMINISTIC_MIGRATION",
    "DETERMINISTIC_MIGRATORS",
    "MODEL_REVIEW_REQUIRED",
    "REUSE_COMPATIBLE",
    "SemanticTransition",
    "SemanticTransitionContract",
    "SemanticTransitionContractChanged",
    "TRAINING_REQUIRED",
    "TRANSITION_CONTRACT_VERSION",
    "TRANSITION_KINDS",
    "demand_allows_scheduling",
    "execute_transition_page",
    "provider_dispatches_for_transition",
    "requires_model_review",
    "semantic_transition_contract",
    "transition_for",
]
