"""Compatibility shim for xauusd_forecaster.news.annotation.storylines."""

from xauusd_forecaster.news.annotation.storylines import (
    ATTACHMENT_KINDS,
    CORE_KINDS,
    COVERAGE_TEMPLATES,
    CURRENT_EVENT_PROMPT_VERSION,
    ENTITY_ALIASES,
    LEGACY_POLICY_STATUS,
    MODEL_PERMISSION,
    OFFICIAL_ORGANIZATIONS,
    RELATIONS,
    ROLE_LABELS,
    STORYLINE_POLICY_VERSION,
    THEMES,
    event_candidate_rows,
    market_reaction_stream_rows,
    storyline_rows,
    temporal_event_graph,
    theme_stream_rows,
    unassigned_event_rows,
)

__all__ = [
    "ATTACHMENT_KINDS",
    "CORE_KINDS",
    "COVERAGE_TEMPLATES",
    "CURRENT_EVENT_PROMPT_VERSION",
    "ENTITY_ALIASES",
    "LEGACY_POLICY_STATUS",
    "MODEL_PERMISSION",
    "OFFICIAL_ORGANIZATIONS",
    "RELATIONS",
    "ROLE_LABELS",
    "STORYLINE_POLICY_VERSION",
    "THEMES",
    "event_candidate_rows",
    "market_reaction_stream_rows",
    "storyline_rows",
    "temporal_event_graph",
    "theme_stream_rows",
    "unassigned_event_rows",
]
