"""Compatibility shim for xauusd_forecaster.training.generation."""

from xauusd_forecaster.training.generation import (
    BROAD_MODEL_FEATURES,
    CROSSFIT_VERSION,
    EVENT_WEIGHTING_VERSION,
    LIVE_GENERATION_STAGE,
    MATERIALIZATION_BATCH_ROWS,
    NEWS_EXPERIMENTAL_MIN_CLUSTERS,
    NEWS_EXPERIMENTAL_MIN_EVENT_DAYS,
    NEWS_MIN_CLUSTERS,
    NEWS_MIN_EVENT_DAYS,
    NEWS_MIN_EXPOSED_ROWS,
    NEWS_TRAINING_ELIGIBLE_STATES,
    PREVIEW_ROWS,
    REQUIRED_GENERATION_IDENTITIES,
    RETRAIN_INTERVAL,
    SHADOW_ROWS,
    SOURCE_WEIGHT_BUDGET,
    TRAINING_MATERIALIZATION_CONTRACT,
    UTC,
    chronological_crossfit_market,
    complete_training_rows,
    news_evidence_status,
    news_input_state_is_training_eligible,
    refresh_training_materialization_state,
    require_current_contract_generation,
    train_due_v2,
)

__all__ = [
    "BROAD_MODEL_FEATURES",
    "CROSSFIT_VERSION",
    "EVENT_WEIGHTING_VERSION",
    "LIVE_GENERATION_STAGE",
    "MATERIALIZATION_BATCH_ROWS",
    "NEWS_EXPERIMENTAL_MIN_CLUSTERS",
    "NEWS_EXPERIMENTAL_MIN_EVENT_DAYS",
    "NEWS_MIN_CLUSTERS",
    "NEWS_MIN_EVENT_DAYS",
    "NEWS_MIN_EXPOSED_ROWS",
    "NEWS_TRAINING_ELIGIBLE_STATES",
    "PREVIEW_ROWS",
    "REQUIRED_GENERATION_IDENTITIES",
    "RETRAIN_INTERVAL",
    "SHADOW_ROWS",
    "SOURCE_WEIGHT_BUDGET",
    "TRAINING_MATERIALIZATION_CONTRACT",
    "UTC",
    "chronological_crossfit_market",
    "complete_training_rows",
    "news_evidence_status",
    "news_input_state_is_training_eligible",
    "refresh_training_materialization_state",
    "require_current_contract_generation",
    "train_due_v2",
]
