"""Deterministic, local architecture extraction and artifact compilation."""

from __future__ import annotations

import ast
import hashlib
import json
import os
import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

_POLICY_PATH = Path(__file__).resolve().parents[1] / "architecture/declarations/package_dependencies.toml"
CANONICAL_PACKAGE_DEPENDENCIES = {
    source: set(targets)
    for source, targets in tomllib.loads(_POLICY_PATH.read_text(encoding="utf-8"))["allowed"].items()
}


GENERATED_HEADER = "Generated by scripts/compile_architecture.py; do not edit."
SOURCE_SUFFIXES = {".py", ".ts", ".tsx", ".mts", ".cts", ".mjs", ".ps1", ".psm1", ".cs", ".sql", ".toml"}
IGNORED_PARTS = {".git", "node_modules", ".next", "dist", ".open-next", "__pycache__"}
SECRET_RE = re.compile(r"(?:-----BEGIN [A-Z ]+PRIVATE KEY-----|(?:api|secret|token|password)[_-]?key\s*[:=])", re.I)
PROCESS_CALLS = {"Thread", "Process", "ThreadPoolExecutor", "ProcessPoolExecutor", "Popen", "run", "check_call", "check_output"}


class ArchitectureCompileError(RuntimeError):
    pass


def _posix(path: Path, root: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def _span(path: str, node: ast.AST, rule: str, **detail: Any) -> dict[str, Any]:
    suffix = detail.get("name") or detail.get("target") or detail.get("table") or ""
    return {
        "id": f"{rule}:{path}:{getattr(node, 'lineno', 1)}:{suffix}",
        "type": rule,
        "path": path,
        "line": getattr(node, "lineno", 1),
        "end_line": getattr(node, "end_lineno", getattr(node, "lineno", 1)),
        "extractor": "python-ast",
        "certainty": "EXACT",
        **detail,
    }


def _literal_string(node: ast.AST) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr) and all(isinstance(item, ast.Constant) and isinstance(item.value, str) for item in node.values):
        return "".join(item.value for item in node.values)
    return None


def _call_name(node: ast.Call) -> str:
    value: ast.AST = node.func
    if isinstance(value, ast.Attribute):
        return value.attr
    if isinstance(value, ast.Name):
        return value.id
    return ""


def _sql_operation(sql: str) -> tuple[str, str] | None:
    patterns = (
        ("SCHEMA_DDL", r"^\s*CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?\s+[`\"\[]?([A-Za-z_]\w*)"),
        ("READ", r"^\s*SELECT\b[\s\S]*?\bFROM\s+[`\"\[]?([A-Za-z_]\w*)"),
        ("WRITE", r"^\s*INSERT\s+INTO\s+[`\"\[]?([A-Za-z_]\w*)"),
        ("WRITE", r"^\s*UPDATE\s+[`\"\[]?([A-Za-z_]\w*)"),
        ("DELETE", r"^\s*DELETE\s+FROM\s+[`\"\[]?([A-Za-z_]\w*)"),
    )
    for operation, pattern in patterns:
        match = re.search(pattern, sql, re.I)
        if match:
            return operation, match.group(1).lower()
    return None


def extract_python(root: Path) -> list[dict[str, Any]]:
    facts: list[dict[str, Any]] = []
    roots = [root / "xauusd_forecaster", root / "scripts"]
    for path in sorted(p for base in roots if base.exists() for p in base.rglob("*.py")):
        rel = _posix(path, root)
        tree = ast.parse(path.read_text(encoding="utf-8-sig"), filename=rel)
        module = rel[:-3].replace("/", ".")
        if module.endswith(".__init__"):
            module = module[:-9]
        package = module.rsplit(".", 1)[0] if "." in module else module
        facts.append({"id": f"python_module:{module}", "type": "python_module", "path": rel, "line": 1,
                      "end_line": max(1, len(path.read_text(encoding="utf-8-sig").splitlines())), "module": module,
                      "package": package, "extractor": "python-ast", "certainty": "EXACT"})
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                facts.append(_span(rel, node, "python_function", name=node.name, module=module, private=node.name.startswith("_")))
            elif isinstance(node, ast.ClassDef):
                facts.append(_span(rel, node, "python_class", name=node.name, module=module, private=node.name.startswith("_")))
            elif isinstance(node, (ast.Import, ast.ImportFrom)):
                targets = [alias.name for alias in node.names] if isinstance(node, ast.Import) else [node.module or ""]
                for target in targets:
                    facts.append(_span(rel, node, "python_import", target=target, module=module))
            elif isinstance(node, (ast.Assign, ast.AnnAssign)):
                targets = node.targets if isinstance(node, ast.Assign) else [node.target]
                if any(isinstance(target, ast.Name) and target.id == "__all__" for target in targets):
                    value = node.value
                    if isinstance(value, (ast.List, ast.Tuple)):
                        for item in value.elts:
                            exported = _literal_string(item)
                            if exported:
                                facts.append(_span(rel, item, "python_export", name=exported, module=module))
            elif isinstance(node, ast.If) and isinstance(node.test, ast.Compare):
                if "__name__" in ast.unparse(node.test) and "__main__" in ast.unparse(node.test):
                    facts.append(_span(rel, node, "python_entry_guard", module=module))
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            call_name = _call_name(node)
            if call_name in PROCESS_CALLS:
                facts.append(_span(rel, node, "python_execution", name=call_name, module=module))
            if call_name == "connect" and node.args:
                facts.append(_span(rel, node, "sqlite_connection", name="connect", module=module))
            if call_name in {"execute", "executemany", "executescript"} and node.args:
                sql = _literal_string(node.args[0])
                if sql is None:
                    facts.append(_span(rel, node, "sql_unresolved", name=call_name, module=module))
                    continue
                parsed = _sql_operation(sql)
                if not parsed:
                    continue
                operation, table = parsed
                facts.append(_span(rel, node, "sql_operation", operation=operation, table=table, module=module))
    return facts


def extract_typescript(root: Path, extractor_script: Path | None = None) -> list[dict[str, Any]]:
    script = extractor_script or Path(__file__).resolve().parents[1] / "web" / "build" / "extract-architecture.mjs"
    if not script.is_file():
        return []
    completed = subprocess.run(
        ["node", str(script), "--root", str(root)], cwd=root / "web", check=False,
        capture_output=True, text=True, encoding="utf-8", timeout=60,
    )
    if completed.returncode:
        raise ArchitectureCompileError(f"TypeScript extractor failed: {completed.stderr.strip()}")
    return json.loads(completed.stdout)["facts"]


def match_selector(facts: list[dict[str, Any]], selector: dict[str, Any]) -> list[dict[str, Any]]:
    """Match one explicit selector without guessing dynamic relationships."""
    supported = {"type", "path", "path_prefix", "module", "route", "symbol", "operation", "table"}
    unknown = set(selector) - supported
    if unknown:
        raise ArchitectureCompileError(f"Unsupported selector fields: {sorted(unknown)}")
    matches = []
    for fact in facts:
        if "path_prefix" in selector and not fact.get("path", "").startswith(str(selector["path_prefix"]).rstrip("/") + "/"):
            continue
        if "symbol" in selector and fact.get("name") != selector["symbol"]:
            continue
        if any(key not in {"path_prefix", "symbol"} and fact.get(key) != value for key, value in selector.items()):
            continue
        matches.append(fact)
    return matches


def require_cardinality(facts: list[dict[str, Any]], selector: dict[str, Any], minimum: int, maximum: int) -> list[dict[str, Any]]:
    matches = match_selector(facts, selector)
    if not minimum <= len(matches) <= maximum:
        raise ArchitectureCompileError(f"Selector matched {len(matches)} facts; expected {minimum}..{maximum}")
    return matches


def validate_writer_authority(facts: list[dict[str, Any]], allowed_writers: dict[str, set[str]]) -> None:
    by_table: dict[str, set[str]] = {}
    for fact in facts:
        if fact.get("type") in {"sql_operation", "d1_sql"} and fact.get("operation") in {"WRITE", "DELETE"} and fact.get("table") not in {"unresolved", "UNRESOLVED"}:
            by_table.setdefault(str(fact["table"]), set()).add(str(fact["path"]))
    for table, writers in by_table.items():
        unexpected = writers - allowed_writers.get(table, set())
        if unexpected:
            raise ArchitectureCompileError(f"Table {table} has undeclared writer(s): {sorted(unexpected)}")


def extract_powershell(root: Path) -> list[dict[str, Any]]:
    facts: list[dict[str, Any]] = []
    bases = [base for base in (root / "windows", root / "scripts") if base.exists()]
    paths = sorted({path for base in bases for suffix in ("*.ps1", "*.psm1") for path in base.rglob(suffix)})
    for path in paths:
        rel = _posix(path, root)
        facts.append({"id": f"powershell_file:{rel}", "type": "powershell_file", "path": rel,
                      "line": 1, "end_line": max(1, len(path.read_text(encoding="utf-8-sig").splitlines())),
                      "extractor": "powershell-neutral-fallback", "certainty": "FALLBACK"})
        for line_no, line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
            for kind, pattern in (
                ("powershell_function", r"^\s*function\s+([\w-]+)"),
                ("powershell_dot_source", r"^\s*\.\s+['\"]?([^'\"\s]+)"),
                ("powershell_process", r"\b(Start-Process)\b"),
            ):
                match = re.search(pattern, line, re.I)
                if match:
                    facts.append({"id": f"{kind}:{rel}:{line_no}:{match.group(1)}", "type": kind, "path": rel,
                                  "line": line_no, "end_line": line_no, "name": match.group(1),
                                  "extractor": "powershell-neutral-fallback", "certainty": "FALLBACK"})
    return facts


def extract_powershell_exact(root: Path) -> list[dict[str, Any]]:
    script = Path(__file__).resolve().with_name("extract_architecture_powershell.ps1")
    executable = "powershell.exe" if os.name == "nt" else "pwsh"
    completed = subprocess.run(
        [executable, "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File", str(script), "-Root", str(root)],
        cwd=root, check=False, capture_output=True, text=True, encoding="utf-8-sig", timeout=60,
    )
    if completed.returncode:
        raise ArchitectureCompileError(f"PowerShell AST extractor failed: {completed.stderr.strip()}")
    return sorted(json.loads(completed.stdout)["facts"], key=lambda item: item["id"])


def extract_csharp(root: Path) -> list[dict[str, Any]]:
    facts: list[dict[str, Any]] = []
    base = root / "ctrader"
    if not base.exists():
        return facts
    for path in sorted(base.rglob("*.cs")):
        rel = _posix(path, root)
        facts.append({"id": f"csharp_file:{rel}", "type": "csharp_file", "path": rel, "line": 1, "end_line": 1,
                      "extractor": "csharp-bounded-inventory", "certainty": "BOUNDED"})
        for line_no, line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
            for kind, pattern in (("csharp_namespace", r"\bnamespace\s+([\w.]+)"), ("csharp_class", r"\bclass\s+(\w+)")):
                match = re.search(pattern, line)
                if match:
                    facts.append({"id": f"{kind}:{rel}:{line_no}:{match.group(1)}", "type": kind, "path": rel,
                                  "line": line_no, "end_line": line_no, "name": match.group(1),
                                  "extractor": "csharp-bounded-inventory", "certainty": "BOUNDED"})
    return facts


def _canonical_area(module: str) -> str | None:
    parts = module.split(".")
    return parts[1] if len(parts) > 1 and parts[0] == "xauusd_forecaster" and parts[1] in CANONICAL_PACKAGE_DEPENDENCIES else None


def dependency_evidence(facts: list[dict[str, Any]], *, closed_world: bool = False) -> dict[str, Any]:
    observed: set[tuple[str, str]] = set()
    unresolved: list[str] = []
    for fact in facts:
        if fact["type"] != "python_import":
            continue
        source = _canonical_area(fact.get("module", "")); target = _canonical_area(fact.get("target", ""))
        if source and target and source != target:
            observed.add((source, target))
        elif source and not fact.get("target"):
            unresolved.append(fact["id"])
    allowed = {(source, target) for source, targets in CANONICAL_PACKAGE_DEPENDENCIES.items() for target in targets}
    explicitly_prohibited = {
        (source, "dashboard") for source in CANONICAL_PACKAGE_DEPENDENCIES if source != "dashboard"
    } | {("decision", "assistant")}
    violations = observed - allowed if closed_world else observed & explicitly_prohibited
    return {
        "observed": [{"from": a, "to": b, "policy": "ALLOWED" if (a, b) in allowed else ("PROHIBITED" if (a, b) in violations else "UNDECLARED")} for a, b in sorted(observed)],
        "allowed_unused": [{"from": a, "to": b} for a, b in sorted(allowed - observed)],
        "unlisted_observed": [{"from": a, "to": b} for a, b in sorted(observed - allowed - violations)],
        "violations": [{"from": a, "to": b} for a, b in sorted(violations)],
        "unresolved": sorted(unresolved),
    }


def source_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file() or any(part in IGNORED_PARTS for part in path.relative_to(root).parts):
            continue
        rel = path.relative_to(root).as_posix()
        if path.suffix.lower() in SOURCE_SUFFIXES or rel == "architecture/declarations/explorer.json":
            files.append(path)
    return sorted(files, key=lambda item: item.relative_to(root).as_posix())


def calculate_digest(root: Path, files: Iterable[Path]) -> tuple[str, list[dict[str, Any]]]:
    digest = hashlib.sha256(); entries = []
    for path in files:
        rel = _posix(path, root)
        # Git may materialize the same tracked text as LF or CRLF. Architecture
        # identity follows repository text, not host checkout conventions.
        data = path.read_text(encoding="utf-8-sig").replace("\r\n", "\n").replace("\r", "\n").encode("utf-8")
        item_hash = hashlib.sha256(data).hexdigest()
        digest.update(rel.encode()); digest.update(b"\0"); digest.update(data); digest.update(b"\0")
        entries.append({"path": rel, "sha256": item_hash, "bytes": len(data)})
    return digest.hexdigest(), entries


def _powershell_digest(root: Path) -> str:
    paths = sorted(list((root / "scripts").rglob("*.ps1")) + list((root / "scripts").rglob("*.psm1")))
    return calculate_digest(root, paths)[0]


def _all_source_paths(facts: list[dict[str, Any]]) -> set[str]:
    return {fact["path"] for fact in facts}


def build_code_hierarchy(root: Path, facts: list[dict[str, Any]]) -> dict[str, Any]:
    migration = root / "docs/reference/MODULE_MIGRATION_MAP.md"
    shim_paths = set(re.findall(r"`([^`]+\.py)`[^\n]*\|\s*THIN_SHIM\s*\|", migration.read_text(encoding="utf-8"), re.I)) if migration.is_file() else set()
    by_surface: dict[str, dict[str, list[dict[str, Any]]]] = {}
    symbol_types = {"python_function", "python_class", "python_entry_guard", "web_page_route", "web_api_route",
                    "powershell_function", "csharp_class", "csharp_namespace"}
    for fact in facts:
        path = str(fact["path"])
        surface = "python" if path.startswith("xauusd_forecaster/") else "web" if path.startswith("web/") else "powershell" if path.endswith((".ps1", ".psm1")) else "ctrader" if path.startswith("ctrader/") else "scripts"
        module = fact.get("module") or path
        by_surface.setdefault(surface, {}).setdefault(str(module), [])
        if fact["type"] in symbol_types:
            by_surface[surface][str(module)].append({key: fact[key] for key in ("id", "type", "path", "line", "end_line") if key in fact} | ({"name": fact["name"]} if "name" in fact else {}) | ({"route": fact["route"]} if "route" in fact else {}))
    children = []
    for surface, modules in sorted(by_surface.items()):
        module_rows = []
        for module, symbols in sorted(modules.items()):
            module_path = next((fact["path"] for fact in facts if fact.get("module") == module), module if "/" in module else "")
            module_rows.append({"id": f"module:{module}", "label": module, "path": module_path,
                                "shim": module_path in shim_paths, "children": sorted(symbols, key=lambda item: item["id"])})
        children.append({"id": f"surface:{surface}", "label": surface, "children": module_rows})
    return {"id": "repository", "label": root.name, "children": children}


def build_artifacts(root: Path) -> dict[str, bytes]:
    config = tomllib.loads((root / "architecture/declarations/system.toml").read_text(encoding="utf-8"))
    declaration = json.loads((root / config["explorer_declaration"]).read_text(encoding="utf-8"))
    nodes = [dict(zip(declaration["node_fields"], row, strict=True)) for row in declaration["nodes"]]
    facts = extract_python(root) + extract_typescript(root) + extract_powershell(root) + extract_csharp(root)
    known_paths = {fact["path"] for fact in facts}
    for declared_path in sorted({value for node in nodes for value in node.get("code_paths", [])}):
        candidate = root / declared_path
        matches = [candidate] if candidate.is_file() else sorted(candidate.rglob("*")) if candidate.is_dir() else []
        for path in matches:
            if path.is_file() and not any(part in IGNORED_PARTS for part in path.relative_to(root).parts):
                rel = _posix(path, root)
                if rel not in known_paths:
                    facts.append({"id": f"source_file:{rel}", "type": "source_file", "path": rel, "line": 1, "end_line": 1,
                                  "extractor": "repository-inventory", "certainty": "EXACT"})
                    known_paths.add(rel)
    facts = sorted(facts, key=lambda item: item["id"])
    binding_config = tomllib.loads((root / "architecture/declarations/bindings.toml").read_text(encoding="utf-8"))
    writer_authority = {item["table"]: set(item["paths"]) for item in binding_config.get("writer_authority", [])}
    scoped_writer_facts = [fact for fact in facts if fact.get("table") in writer_authority]
    validate_writer_authority(scoped_writer_facts, writer_authority)
    paths = _all_source_paths(facts)
    dependencies = dependency_evidence(facts)
    if dependencies["violations"]:
        raise ArchitectureCompileError(f"Prohibited observed imports: {dependencies['violations']}")

    # Reuse the established compact high-level schema as semantic input. Structural
    # code facts and their evidence live in separate bounded lazy artifacts.
    explorer = dict(declaration)
    node_evidence: list[dict[str, Any]] = []
    node_matches: dict[str, list[str]] = {}
    for node in nodes:
        matches: set[str] = set()
        for declared_path in node.get("code_paths", []):
            normalized = declared_path.rstrip("/")
            matches.update(path for path in paths if path == normalized or path.startswith(normalized + "/"))
        node_matches[node["id"]] = sorted(matches)
        required = node.get("implementation_state") == "CURRENT_PATH"
        if required and not matches:
            raise ArchitectureCompileError(f"CURRENT_PATH node {node['id']} has zero source binding matches")
        node_evidence.append({"claim_id": f"node:{node['id']}", "categories": ["DECLARED"] + (["STATIC_MATCH"] if matches else []),
                              "bindings": sorted(matches), "selector": "declared_code_paths", "required": required})
    edges = [dict(zip(declaration["edge_fields"], row, strict=True)) for row in declaration["edges"]]
    edge_evidence = []
    observed_pairs = {(item["from"], item["to"]) for item in dependencies["observed"]}
    for edge in edges:
        context = sorted(set(node_matches.get(edge["from"], []) + node_matches.get(edge["to"], [])))
        categories = ["DECLARED"]
        if edge["id"].startswith("dep-"):
            pair = (edge["from"].removeprefix("package-"), edge["to"].removeprefix("package-"))
            if pair in observed_pairs:
                categories.append("STATIC_MATCH")
        edge_evidence.append({"claim_id": f"edge:{edge['id']}", "categories": categories, "bindings": context,
                              "selector": "endpoint_source_context", "relationship_static_match": "STATIC_MATCH" in categories})

    digest, digest_entries = calculate_digest(root, source_files(root))
    powershell_digest = _powershell_digest(root)
    windows_path = root / "architecture/generated/windows-evidence.json"
    if os.name == "nt":
        windows_evidence = {"schema": "architecture-windows-evidence-v1", "generated_header": GENERATED_HEADER,
                            "powershell_digest": powershell_digest, "status": "CURRENT", "facts": extract_powershell_exact(root)}
    elif windows_path.is_file():
        prior_windows = json.loads(windows_path.read_text(encoding="utf-8"))
        windows_evidence = prior_windows if prior_windows.get("powershell_digest") == powershell_digest else {
            "schema": "architecture-windows-evidence-v1", "generated_header": GENERATED_HEADER,
            "powershell_digest": powershell_digest, "status": "STALE", "facts": []}
    else:
        windows_evidence = {"schema": "architecture-windows-evidence-v1", "generated_header": GENERATED_HEADER,
                            "powershell_digest": powershell_digest, "status": "UNAVAILABLE", "facts": []}
    code_index = {"schema": "architecture-code-index-v1", "generated_header": GENERATED_HEADER, "source_digest": digest,
                  "facts": facts, "hierarchy": build_code_hierarchy(root, facts), "dependencies": dependencies,
                  "counts": {kind: sum(1 for fact in facts if fact["type"] == kind) for kind in sorted({fact["type"] for fact in facts})}}
    evidence = {"schema": "architecture-evidence-index-v1", "generated_header": GENERATED_HEADER, "source_digest": digest,
                "claims": sorted(node_evidence + edge_evidence, key=lambda item: item["claim_id"])}
    digest_doc = {"schema": "architecture-source-digest-v1", "generated_header": GENERATED_HEADER, "source_digest": digest, "files": digest_entries}
    placeholders = {
        "test-evidence.json": {"schema": "architecture-test-evidence-v1", "generated_header": GENERATED_HEADER, "source_digest": digest, "status": "NOT_COLLECTED", "contracts": []},
        "mutation-report.json": {"schema": "architecture-mutation-report-v1", "generated_header": GENERATED_HEADER, "source_digest": digest, "status": "NOT_RUN", "mutations": []},
    }
    documents: dict[str, Any] = {
        "explorer-manifest.json": explorer, "code-index.json": code_index,
        "evidence-index.json": evidence, "source-digest.json": digest_doc,
        "windows-evidence.json": windows_evidence, **placeholders,
    }
    artifacts: dict[str, bytes] = {}
    for name, document in documents.items():
        text = json.dumps(document, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"
        if os.path.isabs(text) or SECRET_RE.search(text):
            raise ArchitectureCompileError(f"Unsafe generated content in {name}")
        artifacts[name] = text.encode("utf-8")
    return artifacts


def generated_differences(root: Path, artifacts: dict[str, bytes]) -> list[str]:
    output = root / "architecture/generated"
    differences = []
    expected_names = set(artifacts)
    for name, data in artifacts.items():
        path = output / name
        if not path.is_file() or path.read_bytes() != data:
            differences.append(name)
    for path in output.glob("*.json"):
        if path.name not in expected_names:
            differences.append(path.name)
    return sorted(set(differences))


def write_artifacts(root: Path, artifacts: dict[str, bytes]) -> None:
    output = root / "architecture/generated"; output.mkdir(parents=True, exist_ok=True)
    for name, data in artifacts.items():
        (output / name).write_bytes(data)
